version: '3.1'

services:
  app_backend:
    build:
      context: ./backend
    entrypoint: ./.docker/entrypoint.sh
    ports:
      - 3002:3002
    depends_on:
      - db

  app_frontend:
    build:
      context: ./frontend/task-manager-app
    ports:
      - 3000:3000
    depends_on:
      - app_backend


  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task_manager